# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(695, 723)
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comLabel = QtWidgets.QLabel(MainWindow)
        self.comLabel.setObjectName("comLabel")
        self.horizontalLayout.addWidget(self.comLabel)
        self.comSelect = QtWidgets.QComboBox(MainWindow)
        self.comSelect.setObjectName("comSelect")
        self.comSelect.addItem("")
        self.comSelect.addItem("")
        self.comSelect.addItem("")
        self.comSelect.addItem("")
        self.comSelect.addItem("")
        self.comSelect.addItem("")
        self.comSelect.addItem("")
        self.comSelect.addItem("")
        self.comSelect.addItem("")
        self.horizontalLayout.addWidget(self.comSelect)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.baudrateLabel = QtWidgets.QLabel(MainWindow)
        self.baudrateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.baudrateLabel.setObjectName("baudrateLabel")
        self.horizontalLayout_2.addWidget(self.baudrateLabel)
        self.baudRateSelect = QtWidgets.QComboBox(MainWindow)
        self.baudRateSelect.setEditable(True)
        self.baudRateSelect.setObjectName("baudRateSelect")
        self.baudRateSelect.addItem("")
        self.baudRateSelect.addItem("")
        self.baudRateSelect.setItemText(1, "")
        self.horizontalLayout_2.addWidget(self.baudRateSelect)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sampleTimeLabel = QtWidgets.QLabel(MainWindow)
        self.sampleTimeLabel.setObjectName("sampleTimeLabel")
        self.horizontalLayout_4.addWidget(self.sampleTimeLabel)
        self.sampleTime = QtWidgets.QLineEdit(MainWindow)
        self.sampleTime.setCursorPosition(4)
        self.sampleTime.setObjectName("sampleTime")
        self.horizontalLayout_4.addWidget(self.sampleTime)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.count = QtWidgets.QComboBox(MainWindow)
        self.count.setEditable(True)
        self.count.setObjectName("count")
        self.count.addItem("")
        self.count.addItem("")
        self.count.addItem("")
        self.count.addItem("")
        self.count.addItem("")
        self.count.addItem("")
        self.count.addItem("")
        self.horizontalLayout_3.addWidget(self.count)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.savePathLabel = QtWidgets.QLabel(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePathLabel.sizePolicy().hasHeightForWidth())
        self.savePathLabel.setSizePolicy(sizePolicy)
        self.savePathLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.savePathLabel.setObjectName("savePathLabel")
        self.horizontalLayout_5.addWidget(self.savePathLabel)
        self.savePath = QtWidgets.QComboBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePath.sizePolicy().hasHeightForWidth())
        self.savePath.setSizePolicy(sizePolicy)
        self.savePath.setEditable(True)
        self.savePath.setObjectName("savePath")
        self.horizontalLayout_5.addWidget(self.savePath)
        self.openPathButton = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openPathButton.sizePolicy().hasHeightForWidth())
        self.openPathButton.setSizePolicy(sizePolicy)
        self.openPathButton.setObjectName("openPathButton")
        self.horizontalLayout_5.addWidget(self.openPathButton)
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 6)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.startSample = QtWidgets.QPushButton(MainWindow)
        self.startSample.setObjectName("startSample")
        self.verticalLayout_2.addWidget(self.startSample)
        self.stopSample = QtWidgets.QPushButton(MainWindow)
        self.stopSample.setEnabled(True)
        self.stopSample.setObjectName("stopSample")
        self.verticalLayout_2.addWidget(self.stopSample)
        self.cleanDataDisplay = QtWidgets.QPushButton(MainWindow)
        self.cleanDataDisplay.setObjectName("cleanDataDisplay")
        self.verticalLayout_2.addWidget(self.cleanDataDisplay)
        self.saveManul = QtWidgets.QPushButton(MainWindow)
        self.saveManul.setObjectName("saveManul")
        self.verticalLayout_2.addWidget(self.saveManul)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textDisplay = QtWidgets.QTextBrowser(MainWindow)
        self.textDisplay.setAutoFillBackground(True)
        self.textDisplay.setObjectName("textDisplay")
        self.verticalLayout.addWidget(self.textDisplay)
        self.graphicsDisplay = QtWidgets.QGraphicsView(MainWindow)
        self.graphicsDisplay.setObjectName("graphicsDisplay")
        self.verticalLayout.addWidget(self.graphicsDisplay)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(MainWindow)
        self.comSelect.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "串口监测工具-xjtu"))
        self.comLabel.setText(_translate("MainWindow", "串口选择:"))
        self.comSelect.setItemText(0, _translate("MainWindow", "COM1"))
        self.comSelect.setItemText(1, _translate("MainWindow", "COM2"))
        self.comSelect.setItemText(2, _translate("MainWindow", "COM3"))
        self.comSelect.setItemText(3, _translate("MainWindow", "COM4"))
        self.comSelect.setItemText(4, _translate("MainWindow", "COM5"))
        self.comSelect.setItemText(5, _translate("MainWindow", "COM6"))
        self.comSelect.setItemText(6, _translate("MainWindow", "COM7"))
        self.comSelect.setItemText(7, _translate("MainWindow", "COM8"))
        self.comSelect.setItemText(8, _translate("MainWindow", "COM9"))
        self.baudrateLabel.setText(_translate("MainWindow", "波特率:"))
        self.baudRateSelect.setItemText(0, _translate("MainWindow", "9600"))
        self.sampleTimeLabel.setText(_translate("MainWindow", "采样时间(ms)"))
        self.sampleTime.setText(_translate("MainWindow", "1000"))
        self.label.setText(_translate("MainWindow", "自动保存间隔数:"))
        self.count.setItemText(0, _translate("MainWindow", "10"))
        self.count.setItemText(1, _translate("MainWindow", "50"))
        self.count.setItemText(2, _translate("MainWindow", "100"))
        self.count.setItemText(3, _translate("MainWindow", "200"))
        self.count.setItemText(4, _translate("MainWindow", "300"))
        self.count.setItemText(5, _translate("MainWindow", "500"))
        self.count.setItemText(6, _translate("MainWindow", "1000"))
        self.savePathLabel.setText(_translate("MainWindow", "保存文件夹:"))
        self.openPathButton.setText(_translate("MainWindow", "..."))
        self.startSample.setText(_translate("MainWindow", "开始采集"))
        self.stopSample.setText(_translate("MainWindow", "停止采样"))
        self.cleanDataDisplay.setText(_translate("MainWindow", "清空显示"))
        self.saveManul.setText(_translate("MainWindow", "手动保存"))


